import { getHealthySession, refreshHealthySession, supabase } from "./supabase";
import type { Action, ActionStatus, AnalyticsPayload, HealthContext, Meal, MealAnalysis, ReferralSummary, StreakSnapshot, User, UserPreferences } from "./api";
import { neulifiApi } from "./api";
import type { PlanId } from "./plans";

function requireClient() { if (!supabase) throw new Error("Supabase is not configured in this environment."); return supabase; }
function isSessionError(message: string) { return /jwt|token|session|auth|issued at future|expired/i.test(message); }
async function withSession<T>(operation: (client: NonNullable<typeof supabase>) => Promise<T>): Promise<T> { const client = requireClient(); const healthySession = await getHealthySession(); if (!healthySession) throw new Error("Your session has expired. Please sign in again."); try { return await operation(client); } catch (firstError) { const message = firstError instanceof Error ? firstError.message : String(firstError); if (!isSessionError(message)) throw firstError; const refreshed = await refreshHealthySession(); if (!refreshed) throw new Error("Your session is no longer valid. Please sign in again."); try { return await operation(client); } catch (secondError) { const secondMessage = secondError instanceof Error ? secondError.message : String(secondError); if (isSessionError(secondMessage)) { await client.auth.signOut(); throw new Error("Your session is out of date. Please sign in again."); } throw secondError; } } }

function cleanList(value: unknown) { return Array.isArray(value) ? value.map(String).map((item) => item.trim()).filter(Boolean).slice(0, 12) : []; }
function nonNegativeNumber(value: unknown, fallback = 0) { const number = Number(value); return Number.isFinite(number) && number >= 0 ? number : fallback; }
export function normalizeReferralSummary(value: unknown): ReferralSummary { const source = value && typeof value === "object" ? value as Record<string, unknown> : {}; const commission = nonNegativeNumber(source.paidCommissionPercent, 30); return { code: typeof source.code === "string" && /^[A-Z0-9_-]{4,32}$/i.test(source.code) ? source.code.toUpperCase() : null, referredUsers: Math.floor(nonNegativeNumber(source.referredUsers)), paidUsers: Math.floor(nonNegativeNumber(source.paidUsers)), paidUsersThisMonth: Math.floor(nonNegativeNumber(source.paidUsersThisMonth)), referredScans: Math.floor(nonNegativeNumber(source.referredScans)), pendingEarnings: nonNegativeNumber(source.pendingEarnings), availableEarnings: nonNegativeNumber(source.availableEarnings), lifetimeEarnings: nonNegativeNumber(source.lifetimeEarnings), paidCommissionPercent: Math.min(100, commission) }; }
function record(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function nullableNumber(value: unknown) { if (value === null || value === undefined || value === "") return null; const number = Number(value); return Number.isFinite(number) ? number : null; }
function analyticsMacro(value: unknown) { const source = record(value); return { proteinG: nullableNumber(source.proteinG ?? source.protein_g), carbsG: nullableNumber(source.carbsG ?? source.carbs_g), fatG: nullableNumber(source.fatG ?? source.fat_g), fiberG: nullableNumber(source.fiberG ?? source.fiber_g), sampleCount: Math.floor(nonNegativeNumber(source.sampleCount ?? source.sample_count)) }; }
export function normalizeAnalytics(value: unknown): AnalyticsPayload { const source = record(value); const chart = record(source.chart); const target = record(chart.target); const series = Array.isArray(chart.series) ? chart.series.map((item) => { const row = record(item); return { capturedAt: String(row.capturedAt ?? row.captured_at ?? ""), label: String(row.label || ""), score: Math.max(0, Math.min(100, Math.round(nonNegativeNumber(row.score)))), rollingAverage: Math.max(0, Math.min(100, nullableNumber(row.rollingAverage ?? row.rolling_average) ?? 0)) }; }).filter((item) => item.capturedAt || item.label) : []; const heatmap = record(source.performanceHeatmap ?? source.performance_heatmap); const buckets = Array.isArray(heatmap.buckets) ? heatmap.buckets.map((item) => { const row = record(item); return { window: String(row.window || "Morning") as AnalyticsPayload["performanceHeatmap"]["buckets"][number]["window"], averageScore: nullableNumber(row.averageScore ?? row.average_score), mealCount: Math.floor(nonNegativeNumber(row.mealCount ?? row.meal_count)) }; }) : []; const blueprint = record(source.optimalBlueprint ?? source.optimal_blueprint); const interval = record(source.intervalPenalty ?? source.interval_penalty); const gap = (item: unknown) => { const row = record(item); return { averageScore: nullableNumber(row.averageScore ?? row.average_score), mealCount: Math.floor(nonNegativeNumber(row.mealCount ?? row.meal_count)) }; }; const volatility = record(source.nutrientVolatility ?? source.nutrient_volatility); const volatilitySeries = Array.isArray(volatility.series) ? volatility.series.map((item) => { const row = record(item); return { capturedAt: String(row.capturedAt ?? row.captured_at ?? ""), label: String(row.label || ""), scoreStddev: nullableNumber(row.scoreStddev ?? row.score_stddev), proteinStddev: nullableNumber(row.proteinStddev ?? row.protein_stddev) }; }).filter((item) => item.capturedAt || item.label) : []; const latest = record(volatility.latest); return { chart: { series, target: { min: nullableNumber(target.min) ?? 70, max: nullableNumber(target.max) ?? 100 } }, performanceHeatmap: { buckets }, optimalBlueprint: { top: analyticsMacro(blueprint.top), bottom: analyticsMacro(blueprint.bottom), sampleCount: Math.floor(nonNegativeNumber(blueprint.sampleCount ?? blueprint.sample_count)) }, intervalPenalty: { longGap: gap(interval.longGap ?? interval.long_gap), shortGap: gap(interval.shortGap ?? interval.short_gap) }, nutrientVolatility: { series: volatilitySeries, latest: { scoreStddev: nullableNumber(latest.scoreStddev ?? latest.score_stddev), proteinStddev: nullableNumber(latest.proteinStddev ?? latest.protein_stddev) } } }; }
export function normalizeHealthContext(value: unknown): HealthContext { const source = value && typeof value === "object" ? value as Record<string, unknown> : {}; return { conditions: cleanList(source.conditions), allergies: cleanList(source.allergies), notes: typeof source.notes === "string" ? source.notes.trim().slice(0, 600) : "" }; }
export function normalizePreferences(value: unknown): UserPreferences { const source = value && typeof value === "object" ? value as Record<string, unknown> : {}; return { ...source, healthContext: normalizeHealthContext(source.healthContext) }; }
function normalizeRegion(value: unknown) { const regions = ["global", "south-asia", "east-asia", "southeast-asia", "europe", "north-america", "latin-america", "mena", "sub-saharan-africa"] as const; return regions.includes(value as typeof regions[number]) ? value as typeof regions[number] : "global"; }
function isNextMealNutritionTask(text: string) { return /\bnext\s+meal\b/i.test(text) && /\b(?:vegetable|vegetables|greens|fruit|fibre|fiber|balanced|balance)\b/i.test(text) && /\b(?:add|include|build|make|plan|choose)\b/i.test(text); }
function isGeneralDailyTask(item: string) { const text = String(item).trim(); const nextMealNutrition = isNextMealNutritionTask(text); if (!text || text.length > 110 || (!nextMealNutrition && !/water|hydrate|walk|movement|move|break|sleep|bedtime|stretch|schedule|routine|habit|breathe|mindful|rest|goal|priority|today|tomorrow|wind down|planning/i.test(text))) return false; if (/\b(?:at|by|before|around)\s+(?:[01]?\d|2[0-3])(?::[0-5]\d)?\s*(?:am|pm)?\b|\b(?:[01]?\d|2[0-3]):[0-5]\d\b/i.test(text)) return false; if (/\b(?:compensate|compensation|burn off|make up for|earn|punish|undo|offset|repay|medication|insulin|dose|blood pressure|blood sugar|diagnos|treatment)\b/i.test(text)) return false; if (/\b(?:serving|portion|cup|gram|grams|ounce|ounces|tablespoon|teaspoon|handful|bowl|amount|quantity)\b/i.test(text)) return false; if (nextMealNutrition) return true; if (/\bmeal\b/i.test(text) && !/\b(?:after|following)\s+(?:this|your)\s+meal\b/i.test(text)) return false; if (/\bgoal\b/i.test(text) && !/\bmeal\b/i.test(text)) return false; return !/\b(food|plate|ingredient|vegetable|greens|fruit|protein|fibre|fiber|sodium|salt|sugar|sauce|dressing|carbohydrate|calorie|portion|snack|allerg|label|dietary|recipe|cook|eat|consume|add|remove|reduce|increase|choose|swap|replace|include|serve|limit|avoid|measure|count|soup|bowl|rice|chicken|tofu|yoga|squat|lunge|push-up|plank|jog|run|cycling|medication|insulin|dose|blood pressure|blood sugar)\b/i.test(text); }
function legacyDailyTasks(recommendations: string[]) { return [...new Set(recommendations.filter((item) => isGeneralDailyTask(item)))].slice(0, 2); }
function normalizeScore(value: unknown) { const score = Number(value); return Number.isFinite(score) ? Math.max(0, Math.min(100, Math.round(score))) : 0; }
function mapAnalysis(row: any): MealAnalysis { const recommendations = cleanList(row?.recommendations); const mealGuidance = cleanList(row?.meal_guidance ?? row?.mealGuidance); const dailyTasks = cleanList(row?.daily_tasks ?? row?.dailyTasks).filter(isGeneralDailyTask); return { rating: row?.rating || "Reasonable", score: normalizeScore(row?.score), indicators: (row?.indicators || {}) as Record<string, number>, explanation: row?.explanation || "", mealGuidance: mealGuidance.length ? mealGuidance : recommendations, dailyTasks: dailyTasks.slice(0, 2), recommendations: recommendations.length ? recommendations : mealGuidance }; }
function mapMeal(row: any, analysisRow: any): Meal | null { if (!analysisRow || typeof analysisRow !== "object") return null; const imageUrl = (Array.isArray(row?.image_urls) ? row.image_urls.map(String).filter(Boolean)[0] : "") || String(row?.image_url || ""); return { id: row.id, userId: row.user_id, imageUrl, imageUrls: imageUrl ? [imageUrl] : [], mealName: row.meal_name, capturedAt: row.captured_at, status: row.status, analysis: mapAnalysis(analysisRow) }; }
function profileFromRow(data: any, fallback: User): User { const preferences = normalizePreferences({ ...(data.preferences || {}), region: data.region || data.preferences?.region, timezone: data.timezone || data.preferences?.timezone }); return { ...fallback, id: data.id, name: data.name || fallback.name, goals: cleanList(data.goals), preferences, region: normalizeRegion(data.region || preferences.region), timezone: data.timezone || String(preferences.timezone || "UTC") }; }
function mapAction(row: any): Action { const completed = row.status === "completed" || Boolean(row.completed); const status: ActionStatus = completed ? "completed" : row.status === "missed" ? "missed" : "upcoming"; return { id: row.id, userId: row.user_id, mealId: row.meal_id, title: row.title, description: row.description || "", completed, status, dueAt: row.due_at || null, createdAt: row.created_at, completedAt: row.completed_at }; }

export async function ensureUserRecords(_userId: string, name = ""): Promise<void> { await neulifiApi.ensureUserRecords(name.trim().slice(0, 120)); }
export async function attributeReferral(_userId: string, code: string): Promise<boolean> { if (!code.trim()) return false; const result = await neulifiApi.attributeReferral(code.trim().slice(0, 32)); return Boolean(result.attributed); }
export async function fetchProfile(userId: string, fallback: User): Promise<User> { return withSession(async (client) => { const { data, error } = await client.from("profiles").select("id,name,goals,preferences,region,timezone").eq("id", userId).maybeSingle(); if (error) throw new Error(`Could not load profile: ${error.message}`); if (!data) return fallback; return profileFromRow(data, fallback); }); }
export async function updateProfile(userId: string, patch: { name?: string; goals?: string[]; preferences?: UserPreferences }, fallback: User): Promise<User> { return withSession(async (client) => { const nextPreferences = patch.preferences ? normalizePreferences(patch.preferences) : undefined; const payload = { id: userId, ...(patch.name === undefined ? {} : { name: patch.name.trim().slice(0, 120) }), ...(patch.goals === undefined ? {} : { goals: cleanList(patch.goals) }), ...(nextPreferences === undefined ? {} : { preferences: nextPreferences, region: normalizeRegion(nextPreferences.region), timezone: String(nextPreferences.timezone || "UTC").slice(0, 80) }) }; const { data, error } = await client.from("profiles").upsert(payload).select("id,name,goals,preferences,region,timezone").single(); if (error || !data) throw new Error(`Could not save profile: ${error?.message || "No profile was returned"}`); return profileFromRow(data, fallback); }); }

export async function fetchMeals(userId: string): Promise<Meal[]> { return withSession(async (client) => { const { data: rows, error } = await client.from("meals").select("id,user_id,image_url,image_urls,meal_name,captured_at,status").eq("user_id", userId).order("captured_at", { ascending: false }).limit(50); if (error) throw new Error(`Could not load meals: ${error.message}`); const meals = rows || []; if (!meals.length) return []; const ids = meals.map((row) => row.id); const { data: analyses, error: analysisError } = await client.from("meal_analyses").select("meal_id,rating,score,indicators,explanation,recommendations,meal_guidance,daily_tasks").in("meal_id", ids); if (analysisError) throw new Error(`Could not load meal analyses: ${analysisError.message}`); const byMeal = new Map((analyses || []).map((row) => [row.meal_id, row])); return meals.map((row) => mapMeal(row, byMeal.get(row.id))).filter((meal): meal is Meal => Boolean(meal)); }); }
export async function fetchActions(userId: string): Promise<Action[]> { return neulifiApi.actions(userId); }
export async function fetchSubscription(userId: string): Promise<{ plan: PlanId; status: string }> { return withSession(async (client) => { const { data, error } = await client.from("subscriptions").select("plan,status").eq("user_id", userId).maybeSingle(); if (error) throw new Error(`Could not load subscription: ${error.message}`); if (!data) return { plan: "free", status: "unavailable" }; const plan = data.plan === "premium" || data.plan === "pro" ? data.plan : "free"; return { plan, status: data.status || "active" }; }); }
export async function createTask(userId: string, title: string, mealId?: string | null, description = "", dueAt?: string | null): Promise<Action> { return withSession(async (client) => { const resolvedDueAt = dueAt || new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(); const { data, error } = await client.from("actions").insert({ user_id: userId, meal_id: mealId || null, title: title.trim().slice(0, 180), description: description.trim().slice(0, 500), due_at: resolvedDueAt, completed: false, status: "upcoming" }).select("id,user_id,meal_id,title,description,completed,status,due_at,created_at,completed_at").single(); if (error || !data) throw new Error(`Could not add task: ${error?.message || "No task was returned"}`); return mapAction(data); }); }
export async function completeTask(_userId: string, actionId: string, completed: boolean): Promise<void> { await neulifiApi.completeAction(actionId, completed); }
export async function deleteTask(userId: string, actionId: string): Promise<void> { return withSession(async (client) => { const { error } = await client.from("actions").delete().eq("id", actionId).eq("user_id", userId); if (error) throw new Error(`Could not delete task: ${error.message}`); }); }
export async function fetchStreak(userId: string): Promise<StreakSnapshot> { return withSession(async (client) => { const { data, error } = await client.rpc("get_streak_snapshot", { p_user_id: userId }); if (error) throw new Error(`Could not load streak: ${error.message}`); const row = Array.isArray(data) ? data[0] : data; return { currentStreak: Number(row?.current_streak || 0), longestStreak: Number(row?.longest_streak || 0), lastActivityDate: row?.last_activity_date || null }; }); }
export async function ensureReferralCode(_userId: string): Promise<string> { const result = await neulifiApi.ensureReferralCode(); if (!result.code) throw new Error("Could not create your referral link: No referral code was returned"); return result.code; }
export async function fetchReferralSummary(_userId: string): Promise<ReferralSummary> { return normalizeReferralSummary(await neulifiApi.referralSummary()); }
export async function fetchAnalytics(_userId: string): Promise<AnalyticsPayload> { return normalizeAnalytics(await neulifiApi.analytics()); }
