import { getHealthySession, refreshHealthySession, supabase } from "./supabase";
import type { Action, ActionStatus, HealthContext, Meal, MealAnalysis, ReferralSummary, StreakSnapshot, User, UserPreferences } from "./api";
import type { PlanId } from "./plans";

function requireClient() { if (!supabase) throw new Error("Supabase is not configured in this environment."); return supabase; }
function isSessionError(message: string) { return /jwt|token|session|auth|issued at future|expired/i.test(message); }
async function withSession<T>(operation: (client: NonNullable<typeof supabase>) => Promise<T>): Promise<T> { const client = requireClient(); const healthySession = await getHealthySession(); if (!healthySession) throw new Error("Your session has expired. Please sign in again."); try { return await operation(client); } catch (firstError) { const message = firstError instanceof Error ? firstError.message : String(firstError); if (!isSessionError(message)) throw firstError; const refreshed = await refreshHealthySession(); if (!refreshed) throw new Error("Your session is no longer valid. Please sign in again."); try { return await operation(client); } catch (secondError) { const secondMessage = secondError instanceof Error ? secondError.message : String(secondError); if (isSessionError(secondMessage)) { await client.auth.signOut(); throw new Error("Your session is out of date. Please sign in again."); } throw secondError; } } }

function cleanList(value: unknown) { return Array.isArray(value) ? value.map(String).map((item) => item.trim()).filter(Boolean).slice(0, 12) : []; }
export function normalizeHealthContext(value: unknown): HealthContext { const source = value && typeof value === "object" ? value as Record<string, unknown> : {}; return { conditions: cleanList(source.conditions), allergies: cleanList(source.allergies), notes: typeof source.notes === "string" ? source.notes.trim().slice(0, 600) : "" }; }
export function normalizePreferences(value: unknown): UserPreferences { const source = value && typeof value === "object" ? value as Record<string, unknown> : {}; return { ...source, healthContext: normalizeHealthContext(source.healthContext) }; }
function normalizeRegion(value: unknown) { const regions = ["global", "south-asia", "east-asia", "southeast-asia", "europe", "north-america", "latin-america", "mena", "sub-saharan-africa"] as const; return regions.includes(value as typeof regions[number]) ? value as typeof regions[number] : "global"; }
function isGeneralDailyTask(item: string) { const text = String(item).trim(); return Boolean(text) && /water|hydrate|walk|movement|move|break|sleep|bedtime|stretch|schedule|routine|habit|breathe|mindful|rest|goal|priority|today|tomorrow/i.test(text) && !/\b(meal|food|plate|ingredient|vegetable|greens|fruit|protein|fibre|fiber|sodium|salt|sugar|sauce|dressing|carbohydrate|calorie|portion|snack|allerg|label|dietary|recipe|cook|eat|consume|add|remove|reduce|increase|choose|swap|replace|include|serve|limit|avoid|measure|count)\b/i.test(text); }
function legacyDailyTasks(recommendations: string[]) { const dayLevel = recommendations.filter((item) => isGeneralDailyTask(item)); const tasks = [...dayLevel]; if (!tasks.some((item) => /water|hydrate/i.test(item))) tasks.push("Fill a water bottle and finish it by evening."); if (!tasks.some((item) => /walk|movement|break/i.test(item))) tasks.push("Take a 10-minute walk during your afternoon."); return [...new Set(tasks)].slice(0, 4); }
function normalizeScore(value: unknown) { const score = Number(value); return Number.isFinite(score) ? Math.max(0, Math.min(100, Math.round(score))) : 0; }
function mapAnalysis(row: any): MealAnalysis { const recommendations = cleanList(row?.recommendations); const mealGuidance = cleanList(row?.meal_guidance ?? row?.mealGuidance); const dailyTasks = cleanList(row?.daily_tasks ?? row?.dailyTasks).filter(isGeneralDailyTask); return { rating: row?.rating || "Reasonable", score: normalizeScore(row?.score), indicators: (row?.indicators || {}) as Record<string, number>, explanation: row?.explanation || "", mealGuidance: mealGuidance.length ? mealGuidance : recommendations, dailyTasks: dailyTasks.length ? dailyTasks : legacyDailyTasks(recommendations), recommendations: recommendations.length ? recommendations : mealGuidance }; }
function mapMeal(row: any, analysisRow: any): Meal | null { if (!analysisRow || typeof analysisRow !== "object") return null; const imageUrl = (Array.isArray(row?.image_urls) ? row.image_urls.map(String).filter(Boolean)[0] : "") || String(row?.image_url || ""); return { id: row.id, userId: row.user_id, imageUrl, imageUrls: imageUrl ? [imageUrl] : [], mealName: row.meal_name, capturedAt: row.captured_at, status: row.status, analysis: mapAnalysis(analysisRow) }; }
function profileFromRow(data: any, fallback: User): User { const preferences = normalizePreferences({ ...(data.preferences || {}), region: data.region || data.preferences?.region, timezone: data.timezone || data.preferences?.timezone }); return { ...fallback, id: data.id, name: data.name || fallback.name, goals: cleanList(data.goals), preferences, region: normalizeRegion(data.region || preferences.region), timezone: data.timezone || String(preferences.timezone || "UTC") }; }
function mapAction(row: any): Action { const completed = row.status === "completed" || Boolean(row.completed); const status: ActionStatus = completed ? "completed" : row.status === "missed" ? "missed" : "upcoming"; return { id: row.id, userId: row.user_id, mealId: row.meal_id, title: row.title, description: row.description || "", completed, status, dueAt: row.due_at || null, createdAt: row.created_at, completedAt: row.completed_at }; }

export async function ensureUserRecords(userId: string, name = ""): Promise<void> { return withSession(async (client) => { const { error } = await client.rpc("ensure_user_records", { p_user_id: userId, p_name: name.trim().slice(0, 120) }); if (error) throw new Error(`Could not prepare your account data: ${error.message}`); }); }
export async function attributeReferral(userId: string, code: string): Promise<boolean> { if (!code.trim()) return false; return withSession(async (client) => { const { data, error } = await client.rpc("attribute_referral", { p_user_id: userId, p_code: code.trim().slice(0, 32) }); if (error) throw new Error(`Could not save referral attribution: ${error.message}`); return Boolean(data); }); }
export async function fetchProfile(userId: string, fallback: User): Promise<User> { return withSession(async (client) => { const { data, error } = await client.from("profiles").select("id,name,goals,preferences,region,timezone").eq("id", userId).maybeSingle(); if (error) throw new Error(`Could not load profile: ${error.message}`); if (!data) return fallback; return profileFromRow(data, fallback); }); }
export async function updateProfile(userId: string, patch: { name?: string; goals?: string[]; preferences?: UserPreferences }, fallback: User): Promise<User> { return withSession(async (client) => { const nextPreferences = patch.preferences ? normalizePreferences(patch.preferences) : undefined; const payload = { id: userId, ...(patch.name === undefined ? {} : { name: patch.name.trim().slice(0, 120) }), ...(patch.goals === undefined ? {} : { goals: cleanList(patch.goals) }), ...(nextPreferences === undefined ? {} : { preferences: nextPreferences, region: normalizeRegion(nextPreferences.region), timezone: String(nextPreferences.timezone || "UTC").slice(0, 80) }) }; const { data, error } = await client.from("profiles").upsert(payload).select("id,name,goals,preferences,region,timezone").single(); if (error || !data) throw new Error(`Could not save profile: ${error?.message || "No profile was returned"}`); return profileFromRow(data, fallback); }); }

export async function fetchMeals(userId: string): Promise<Meal[]> { return withSession(async (client) => { const { data: rows, error } = await client.from("meals").select("id,user_id,image_url,image_urls,meal_name,captured_at,status").eq("user_id", userId).order("captured_at", { ascending: false }).limit(50); if (error) throw new Error(`Could not load meals: ${error.message}`); const meals = rows || []; if (!meals.length) return []; const ids = meals.map((row) => row.id); const { data: analyses, error: analysisError } = await client.from("meal_analyses").select("meal_id,rating,score,indicators,explanation,recommendations,meal_guidance,daily_tasks").in("meal_id", ids); if (analysisError) throw new Error(`Could not load meal analyses: ${analysisError.message}`); const byMeal = new Map((analyses || []).map((row) => [row.meal_id, row])); return meals.map((row) => mapMeal(row, byMeal.get(row.id))).filter((meal): meal is Meal => Boolean(meal)); }); }
export async function fetchActions(userId: string): Promise<Action[]> { return withSession(async (client) => { const { error: missedError } = await client.rpc("mark_missed_tasks", { p_user_id: userId }); if (missedError) throw new Error(`Could not refresh task status: ${missedError.message}`); const { data, error } = await client.from("actions").select("id,user_id,meal_id,title,description,completed,status,due_at,created_at,completed_at").eq("user_id", userId).order("status", { ascending: true }).order("due_at", { ascending: true, nullsFirst: false }).limit(100); if (error) throw new Error(`Could not load tasks: ${error.message}`); return (data || []).map(mapAction); }); }
export async function fetchSubscription(userId: string): Promise<{ plan: PlanId; status: string }> { return withSession(async (client) => { const { data, error } = await client.from("subscriptions").select("plan,status").eq("user_id", userId).maybeSingle(); if (error) throw new Error(`Could not load subscription: ${error.message}`); if (!data) return { plan: "free", status: "unavailable" }; const plan = data.plan === "premium" || data.plan === "pro" ? data.plan : "free"; return { plan, status: data.status || "active" }; }); }
export async function createTask(userId: string, title: string, mealId?: string | null, description = "", dueAt?: string | null): Promise<Action> { return withSession(async (client) => { const resolvedDueAt = dueAt || new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(); const { data, error } = await client.from("actions").insert({ user_id: userId, meal_id: mealId || null, title: title.trim().slice(0, 180), description: description.trim().slice(0, 500), due_at: resolvedDueAt, completed: false, status: "upcoming" }).select("id,user_id,meal_id,title,description,completed,status,due_at,created_at,completed_at").single(); if (error || !data) throw new Error(`Could not add task: ${error?.message || "No task was returned"}`); return mapAction(data); }); }
export async function completeTask(userId: string, actionId: string, completed: boolean): Promise<void> { return withSession(async (client) => { const { error } = await client.rpc("complete_action", { p_action_id: actionId, p_completed: completed }); if (error) throw new Error(`Could not update task: ${error.message}`); }); }
export async function deleteTask(userId: string, actionId: string): Promise<void> { return withSession(async (client) => { const { error } = await client.from("actions").delete().eq("id", actionId).eq("user_id", userId); if (error) throw new Error(`Could not delete task: ${error.message}`); }); }
export async function fetchStreak(userId: string): Promise<StreakSnapshot> { return withSession(async (client) => { const { data, error } = await client.rpc("get_streak_snapshot", { p_user_id: userId }); if (error) throw new Error(`Could not load streak: ${error.message}`); const row = Array.isArray(data) ? data[0] : data; return { currentStreak: Number(row?.current_streak || 0), longestStreak: Number(row?.longest_streak || 0), lastActivityDate: row?.last_activity_date || null }; }); }
export async function ensureReferralCode(userId: string): Promise<string> { return withSession(async (client) => { const { data, error } = await client.rpc("ensure_referral_code", { p_user_id: userId }); if (error || !data) throw new Error(`Could not create your referral link: ${error?.message || "No referral code was returned"}`); return String(data); }); }
export async function fetchReferralSummary(userId: string): Promise<ReferralSummary> { return withSession(async (client) => { const { data, error } = await client.rpc("get_referral_summary", { p_user_id: userId }); if (error) throw new Error(`Could not load referral summary: ${error.message}`); const summary = (data || {}) as Record<string, unknown>; return { code: summary.code ? String(summary.code) : null, referredUsers: Number(summary.referredUsers || 0), paidUsers: Number(summary.paidUsers || 0), paidUsersThisMonth: Number(summary.paidUsersThisMonth || 0), referredScans: Number(summary.referredScans || 0), pendingEarnings: Number(summary.pendingEarnings || 0), availableEarnings: Number(summary.availableEarnings || 0), lifetimeEarnings: Number(summary.lifetimeEarnings || 0), standardProCommission: Number(summary.standardProCommission || 1), standardPremiumCommission: Number(summary.standardPremiumCommission || 3), highVolumeProCommission: Number(summary.highVolumeProCommission || 2), highVolumePremiumCommission: Number(summary.highVolumePremiumCommission || 5), highVolumeThreshold: Number(summary.highVolumeThreshold || 100) }; }); }
