import { analysisSchema, buildMealPrompt, normalizeMealAnalysis } from "../../server/normalize.mjs";

const groqEndpoint = "https://api.groq.com/openai/v1/chat/completions";
const geminiEndpoint = "https://generativelanguage.googleapis.com/v1beta/models";
function env(name, fallback = "") { return Netlify.env.get(name) || fallback; }
function json(status, payload) { return new Response(JSON.stringify(payload), { status, headers: { "content-type": "application/json; charset=utf-8" } }); }
async function authUser(request) { const authorization = request.headers.get("authorization") || ""; if (!authorization.startsWith("Bearer ")) { if (env("REQUIRE_AUTH", "false") === "true") throw Object.assign(new Error("Authentication required"), { status: 401 }); return null; } const supabaseUrl = env("SUPABASE_URL"); const supabaseKey = env("SUPABASE_PUBLISHABLE_KEY"); if (!supabaseUrl || !supabaseKey) throw Object.assign(new Error("Supabase server authentication is not configured"), { status: 503 }); const response = await fetch(`${supabaseUrl}/auth/v1/user`, { headers: { apikey: supabaseKey, authorization } }); if (!response.ok) throw Object.assign(new Error("Invalid or expired authentication session"), { status: 401 }); return response.json(); }
async function imagePart(imageUrl) { if (imageUrl.startsWith("data:")) { const match = imageUrl.match(/^data:([^;]+);base64,(.+)$/); if (!match) throw new Error("Invalid image data URL"); return { mimeType: match[1], base64: match[2] }; } const response = await fetch(imageUrl, { signal: AbortSignal.timeout(15000) }); if (!response.ok) throw new Error(`Meal image could not be fetched (${response.status})`); return { mimeType: response.headers.get("content-type")?.split(";")[0] || "image/jpeg", base64: Buffer.from(await response.arrayBuffer()).toString("base64") }; }
async function analyzeGroq(image, mealName, context, apiKey, model) { const response = await fetch(groqEndpoint, { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${apiKey}` }, signal: AbortSignal.timeout(60000), body: JSON.stringify({ model, temperature: 0.2, top_p: 0.8, max_completion_tokens: 2600, reasoning_format: "hidden", reasoning_effort: "none", response_format: { type: "json_object" }, messages: [{ role: "user", content: [{ type: "text", text: buildMealPrompt(mealName, context) }, { type: "image_url", image_url: { url: `data:${image.mimeType};base64,${image.base64}` } }] }] }) }); if (!response.ok) throw new Error(`Groq analysis failed (${response.status})`); const payload = await response.json(); const content = payload.choices?.[0]?.message?.content; if (!content) throw new Error("Groq returned no analysis"); return normalizeMealAnalysis(content); }
async function analyzeGemini(image, mealName, context, apiKey, model) { const response = await fetch(`${geminiEndpoint}/${model}:generateContent?key=${encodeURIComponent(apiKey)}`, { method: "POST", headers: { "content-type": "application/json" }, signal: AbortSignal.timeout(60000), body: JSON.stringify({ contents: [{ role: "user", parts: [{ inline_data: { mime_type: image.mimeType, data: image.base64 } }, { text: buildMealPrompt(mealName, context) }] }], systemInstruction: { parts: [{ text: "You are Nuelifi. Never diagnose or prescribe. Keep mealGuidance separate from dailyTasks. DailyTasks must be standalone day-level actions and must not tell the user to edit a plate or inspect a specific food, nutrient, ingredient, sauce, or portion." }] }, generationConfig: { temperature: 0.2, responseMimeType: "application/json", responseSchema: analysisSchema() } }) }); if (!response.ok) throw new Error(`Gemini analysis failed (${response.status})`); const payload = await response.json(); const text = payload.candidates?.[0]?.content?.parts?.map((part) => part.text || "").join(""); if (!text) throw new Error("Gemini returned no analysis"); return normalizeMealAnalysis(text); }

export default async function handler(request) { if (request.method === "OPTIONS") return new Response(null, { status: 204 }); if (request.method !== "POST") return json(405, { error: "Method not allowed" }); try { const input = await request.json(); if (!input?.imageUrl) return json(400, { error: "imageUrl is required" }); const tokenUser = await authUser(request); if (tokenUser && input.userId && tokenUser.id !== input.userId) return json(403, { error: "You cannot analyze for another user" }); const image = await imagePart(String(input.imageUrl)); const mealName = String(input.mealName || "Meal").slice(0, 120); const context = input.context && typeof input.context === "object" ? input.context : {}; let analysis; let provider; let lastError; const groqKey = env("GROQ_API_KEY"); if (groqKey) { try { analysis = await analyzeGroq(image, mealName, context, groqKey, env("GROQ_MODEL", "qwen/qwen3.6-27b")); provider = "groq"; } catch (error) { lastError = error; } } if (!analysis) { const geminiKey = env("GEMINI_API_KEY"); if (geminiKey) { for (const model of [...new Set([env("GEMINI_MODEL", "gemini-3.7-flash"), ...env("GEMINI_FALLBACK_MODELS", "gemini-3.5-flash,gemini-2.5-flash").split(",").map((value) => value.trim()).filter(Boolean)])]) { try { analysis = await analyzeGemini(image, mealName, context, geminiKey, model); provider = "gemini"; break; } catch (error) { lastError = error; } } } } if (!analysis) throw lastError || new Error("No AI provider is configured"); return json(200, { id: `analysis-${Date.now()}`, userId: tokenUser?.id || input.userId || "", imageUrl: input.imageUrl, mealName, capturedAt: new Date().toISOString(), status: "analysed", analysis, provider }); } catch (error) { return json(error?.status || (error?.name === "AbortError" ? 504 : 502), { error: error instanceof Error ? error.message : "Meal analysis failed" }); } }
export const config = { path: "/api/analyze" };
