import { useState } from "react";
import type { Meal, RegionId } from "../lib/api";
import { getMealExamples } from "../lib/regionalExamples";

export interface MealDraft { imageUrl: string; mealName: string; }
export interface ResultAction { id: string; title: string; detail: string; completed: boolean; added: boolean; }

const icon = (name: string, size = 18) => { const paths: Record<string, string> = { camera: "M4 7.5h3l1.2-2h7.6l1.2 2h3A1.8 1.8 0 0 1 22 9.3v9.2a1.8 1.8 0 0 1-1.8 1.8H3.8A1.8 1.8 0 0 1 2 18.5V9.3a1.8 1.8 0 0 1 1.8-1.8zM12 17a3.6 3.6 0 1 0 0-7.2A3.6 3.6 0 0 0 12 17z", upload: "M12 16V4m0 0L7 9m5-5 5 5M4 20h16", check: "M20 6 9 17l-5-5", arrow: "m9 18 6-6-6-6", leaf: "M20 4C11 4 5 8 5 14c0 3 2 5 5 5 6 0 10-6 10-15zM4 21c2-5 6-8 11-11" }; return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name] || paths.leaf}/></svg>; };
function Badge({ children }: { children: React.ReactNode }) { return <span className="badge badge-green">{children}</span>; }
function metric(indicators: Record<string, number>, key: string, unit: string) { const value = indicators[key]; if (!Number.isFinite(value)) return "—"; const rounded = Number.isInteger(value) ? value : Number(value.toFixed(1)); return `~${rounded} ${unit}`; }

export function MealCapture({ onReady, region = "global" }: { onReady: (draft: MealDraft) => void; region?: RegionId }) { const examples = getMealExamples(region); const [selected, setSelected] = useState<string | null>(null); const [name, setName] = useState(""); const chooseFile = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { setSelected(String(reader.result)); setName(file.name.replace(/\.[^/.]+$/, "")); }; reader.readAsDataURL(file); }; const chooseExample = (example: typeof examples[number]) => { setSelected(example.image); setName(example.name); }; return <div className="screen"><p className="screen-intro">Take a photo or upload an image of your meal. Neulifi gives you a clear, honest assessment with practical next steps — no guilt, just useful information.</p><div className="upload-zone">{selected ? <img src={selected} alt="Selected meal"/> : <><span className="upload-icon">{icon("camera", 28)}</span><strong>Your meal photo will appear here</strong><small>Use the options below to add a photo</small></>}</div><div className="upload-actions"><label className="button button-dark">{icon("camera", 17)} Take photo<input className="sr-only" type="file" accept="image/*" capture="environment" onChange={chooseFile}/></label><label className="button button-soft">{icon("upload", 17)} Upload<input className="sr-only" type="file" accept="image/*" onChange={chooseFile}/></label></div><p className="or-label">OR TRY AN EXAMPLE</p><div className="example-row">{examples.map((example) => <button type="button" key={example.name} aria-pressed={selected === example.image} onClick={() => chooseExample(example)} aria-label={`Use example: ${example.name}`}><img src={example.image} alt={example.name}/></button>)}</div>{selected && <button type="button" className="button button-green analyse-submit" onClick={() => onReady({ imageUrl: selected, mealName: name || "New meal" })}>Analyse meal <span>{icon("arrow", 17)}</span></button>}</div>; }

export function MealPreview({ draft, onRetake, onAnalyse, error = "" }: { draft: MealDraft; onRetake: () => void; onAnalyse: () => void; error?: string }) { return <div className="screen flow-screen">{error && <div className="data-note data-error" role="alert">{error}</div>}<p className="screen-intro">Make sure your entire meal is visible before continuing.</p><div className="preview-image-wrap"><img src={draft.imageUrl} alt="Meal preview"/><span className="preview-chip">Photo preview</span></div><h2 className="flow-meal-name">{draft.mealName}</h2><p className="muted flow-help">Neulifi will use this image to prepare a simple assessment and practical next steps.</p><div className="flow-actions"><button type="button" className="button button-soft" onClick={onRetake}>Retake</button><button type="button" className="button button-dark" onClick={onAnalyse}>Analyse meal {icon("arrow", 16)}</button></div></div>; }

export function Analysing() { return <div className="screen analysing-screen" role="status" aria-live="polite"><div className="analysis-orbit"><span/><span/><span/></div><h1>Analysing your meal</h1><p>Neulifi is looking at your meal and preparing clear observations and one practical next step.</p><div className="analysis-progress"><span/></div><small>This usually takes a few seconds</small></div>; }

export function MealResults({ meal, actions, onAction, onAddTask, onDone }: { meal: Meal; actions: ResultAction[]; onAction: (id: string) => void; onAddTask: () => void; onDone: () => void }) {
  const indicators = meal.analysis.indicators || {};
  const portionBalance = Number.isFinite(indicators.portionBalance) ? indicators.portionBalance : null;
  const portionBalanceLabel = portionBalance === null ? "—" : `~${portionBalance > 3 ? Math.round(portionBalance) : Number(portionBalance.toFixed(1))}/${portionBalance > 3 ? 100 : 3}`;
  const values = [
    { label: "Calories", value: metric(indicators, "calories", "kcal") },
    { label: "Protein", value: metric(indicators, "protein", "g") },
    { label: "Carbohydrates", value: metric(indicators, "carbohydrates", "g") },
    { label: "Fat", value: metric(indicators, "fats", "g") },
    { label: "Fibre", value: metric(indicators, "fibre", "g") },
    { label: "Sugar", value: metric(indicators, "sugar", "g") },
    { label: "Sodium", value: metric(indicators, "sodium", "mg") },
    { label: "Vegetables", value: metric(indicators, "vegetables", "servings") },
    { label: "Portion balance", value: portionBalanceLabel },
  ];
  const good = [
    Number(indicators.protein) >= 20 ? "Good protein source" : "Includes a protein source",
    Number(indicators.vegetables) >= 2 ? "Contains vegetables" : "Includes some plant food",
    Number(indicators.fibre) >= 5 ? "Provides useful fibre" : "A clear meal foundation",
  ];
  const improve = [
    Number(indicators.vegetables) < 3 ? "Add another serving of vegetables for more fibre and micronutrients." : "Keep the vegetable variety going across the day.",
    Number(indicators.fibre) < 8 ? "Fibre could be higher with beans, whole grains, fruit, or another vegetable." : "Your fibre estimate is a strength to maintain.",
    Number(indicators.sodium) > 800 ? "Consider a lower-sodium option or smaller amount of sauces next time." : "Use the recommendations below for the most relevant next step.",
  ];
  const allAdded = actions.length > 0 && actions.every((action) => action.added);
  return <div className="screen results-screen"><div className="result-hero"><img src={meal.imageUrl} alt={meal.mealName}/><div className="result-hero-copy"><p className="eyebrow light">MEAL BALANCE</p><Badge>{meal.analysis.rating}</Badge><div className="result-score">{meal.analysis.score}<small>/100</small></div></div></div><h1 className="result-title">Here is what Neulifi noticed</h1><p className="result-summary">{meal.analysis.explanation}</p><section className="result-section"><h3>Approximate signals from your photo</h3><div className="nutrition-grid">{values.map((item) => <div className="nutrition-item" key={item.label}><small>{item.label}</small><strong>{item.value}</strong></div>)}</div></section><section className="result-section"><h3>What is looking good</h3><div className="positive-list">{good.map((item) => <p key={item}><span>{icon("check", 14)}</span>{item}</p>)}</div></section><section className="result-section"><h3>One or two ways to improve</h3><div className="improve-list">{improve.map((item) => <p key={item}>• {item}</p>)}</div></section><section className="result-section recommendations"><h3>How could you improve this meal?</h3>{meal.analysis.mealGuidance.map((item, index) => <div className="recommendation" key={`${item}-${index}`}><span>{index + 1}</span><div><strong>{item}</strong><small>Meal-specific guidance — not added to tasks.</small></div></div>)}</section><section className="result-section result-actions"><div className="result-actions-heading"><h3>Simple steps for today</h3><button type="button" className={`add-task-button ${allAdded ? "added" : ""}`} onClick={onAddTask} disabled={allAdded}>{allAdded ? "Added to tasks" : "+ Add to tasks"}</button></div>{actions.map((action) => <button type="button" className={`result-action ${action.completed ? "completed" : ""} ${!action.added ? "pending-task" : ""}`} key={action.id} disabled={!action.added} onClick={() => onAction(action.id)}><span className="result-checkbox">{action.completed ? "✓" : ""}</span><span>{action.title}</span></button>)}</section><div className="bottom-guidance"><strong>You don't need to change everything.</strong><span>Start with one improvement.</span></div><button type="button" className="button button-green done-button" onClick={onDone}>Done — back to dashboard</button></div>;
}
