import { getPlan, plans, type PlanId } from "../lib/plans";
import { BrandMark } from "./BrandMark";

type PublicPage = "landing" | "features" | "pricing";

type PublicSiteProps = {
  page: PublicPage;
  onNavigate: (page: PublicPage) => void;
  onAuth: (mode: "signin" | "signup") => void;
  onPreview: () => void;
};

export function PublicSite({ page, onNavigate, onAuth, onPreview }: PublicSiteProps) {
  return <div className="public-site">
    <PublicNav page={page} onNavigate={onNavigate} onAuth={onAuth} />
    {page === "landing" ? <Landing onNavigate={onNavigate} onAuth={onAuth} /> : page === "features" ? <Features onAuth={onAuth} /> : <Pricing onAuth={onAuth} />}
    <PublicFooter onNavigate={onNavigate} onAuth={onAuth} />
  </div>;
}

function PublicNav({ page, onNavigate, onAuth }: { page: PublicPage; onNavigate: (page: PublicPage) => void; onAuth: (mode: "signin" | "signup") => void }) {
  return <header className="public-nav">
    <button className="public-brand" type="button" onClick={() => onNavigate("landing")}><BrandMark className="brand-logo"/><strong>Neulifi</strong></button>
    <nav className="public-links" aria-label="Public navigation"><button className={page === "features" ? "active" : ""} type="button" onClick={() => onNavigate("features")}>How it works</button><button className={page === "pricing" ? "active" : ""} type="button" onClick={() => onNavigate("pricing")}>Plans</button></nav>
    <div className="public-actions"><button className="public-login" type="button" onClick={() => onAuth("signin")}>Sign in</button><button className="button button-green public-cta" type="button" onClick={() => onAuth("signup")}>Get started</button></div>
  </header>;
}

function Landing({ onNavigate, onAuth }: { onNavigate: (page: PublicPage) => void; onAuth: (mode: "signin" | "signup") => void }) {
  return <main className="public-main public-landing">
    <section className="public-hero public-hero-premium redesigned-hero">
      <div className="public-hero-copy">
        <span className="public-kicker"><span className="public-kicker-dot" />A BETTER EVERYDAY LOOP</span>
        <h1>Better food.<br/>Better habits.<br/><em>Better health.</em></h1>
        <p className="public-hero-lede">Neulifi turns a meal photo into clear observations and one practical next step—then helps you connect food, movement, and patterns over time.</p>
        <div className="public-hero-actions"><button className="button button-green public-primary-button" type="button" onClick={() => onAuth("signup")}>Get started <span aria-hidden="true">→</span></button><button className="public-secondary-cta" type="button" onClick={() => onNavigate("features")}>See how it works <span aria-hidden="true">↗</span></button></div>
        <div className="public-trust-row"><span>Private by design</span><span>Practical, not prescriptive</span><span>Built for real meals</span></div>
      </div>
      <ProductPreview />
    </section>

    <section className="public-manifesto" aria-labelledby="manifesto-title"><div><span className="public-kicker">THE IDEA</span><h2 id="manifesto-title">You do not need a perfect diet.</h2></div><div><p className="public-manifesto-lede">You need better information and a better next choice.</p><p>Neulifi is for the space between “I should eat better” and “what could I actually do today?” It keeps the useful signal, leaves the guilt behind, and helps small choices become a pattern.</p></div></section>

    <section className="public-loop-section public-section" aria-labelledby="loop-title"><div className="public-section-heading"><span className="public-kicker">THE NEULIFI LOOP</span><h2 id="loop-title">From a picture to a pattern.</h2><p>One calm workflow for noticing what matters and doing something with it.</p></div><div className="public-loop-grid"><LoopStep number="01" label="Scan" copy="Take a picture of the meal you are actually having."/><LoopStep number="02" label="Understand" copy="See useful signals without pretending a photo is a lab test."/><LoopStep number="03" label="Adjust" copy="Get one or two realistic ways to make the next choice a little better."/><LoopStep number="04" label="Move" copy="Add everyday movement without treating exercise as payment for food."/><LoopStep number="05" label="Track" copy="Keep meals, actions, and context together in your private space."/><LoopStep number="06" label="Improve" copy="Let repeated small choices shape a clearer picture over time."/></div></section>

    <section className="public-meal-section public-section" aria-labelledby="meal-title"><div className="public-meal-visual"><div className="public-visual-caption"><span>EXAMPLE MEAL</span><small>South Asian table</small></div><div className="public-plate"><div className="public-plate-food public-food-rice">Rice</div><div className="public-plate-food public-food-curry">Chicken curry</div><div className="public-plate-food public-food-dhal">Dhal</div><div className="public-plate-food public-food-greens">Vegetables</div></div><p className="public-visual-footnote">Approximate signals from a photo—not a nutrition label.</p></div><div className="public-meal-copy"><span className="public-kicker">SCAN → UNDERSTAND</span><h2 id="meal-title">See what you are actually eating.</h2><p>Rice, curry, dhal, sambol, roti, string hoppers, kottu—familiar food belongs here. Neulifi is designed to understand the meal in front of you, not push you toward one narrow idea of “healthy.”</p><div className="public-signal-list"><Signal label="Protein" value="Good" tone="good"/><Signal label="Vegetable variety" value="Good" tone="good"/><Signal label="Fibre" value="Could be higher" tone="watch"/><Signal label="Sodium" value="Moderate" tone="neutral"/></div></div></section>

    <section className="public-adjust-section public-section" aria-labelledby="adjust-title"><div className="public-section-heading"><span className="public-kicker">ADJUST, WITHOUT GUILT</span><h2 id="adjust-title">Make the next meal a little better.</h2><p>You do not have to change everything. Keep the meal. Keep the culture. Start with one useful adjustment.</p></div><div className="public-before-after"><div className="public-before"><span>YOUR MEAL</span><strong>Rice · chicken curry · dhal · vegetables</strong><small>Vegetable variety: good<br/>Fibre: could be higher</small></div><div className="public-arrow" aria-hidden="true">→</div><div className="public-after"><span>ONE SIMPLE IMPROVEMENT</span><strong>Add another serving of vegetables.</strong><small>Or choose a less salty preparation next time.</small></div></div></section>

    <section className="public-movement-section public-section" aria-labelledby="movement-title"><div className="public-movement-copy"><span className="public-kicker">MOVE WITH YOUR DAY</span><h2 id="movement-title">Food is part of the picture, not a debt to repay.</h2><p>Walking to the bus, cycling, a game, household work, a gym session—movement can fit naturally around meals. Neulifi helps you notice the connection without turning the day into a step-count competition.</p><button className="text-button public-text-button" type="button" onClick={() => onNavigate("features")}>Explore the approach <span aria-hidden="true">→</span></button></div><div className="public-day-line"><div className="public-day-point"><span>BREAKFAST</span><strong>Start the day</strong></div><i/><div className="public-day-point"><span>LUNCH</span><strong>Keep going</strong></div><i className="active"/><div className="public-day-point"><span>20-MIN WALK</span><strong>Add movement</strong></div><i/><div className="public-day-point"><span>DINNER</span><strong>Notice the pattern</strong></div></div></section>

    <section className="public-pattern-section public-section" aria-labelledby="pattern-title"><div className="public-pattern-header"><div><span className="public-kicker">TRACK → IMPROVE</span><h2 id="pattern-title">Small choices. Repeated often.</h2></div><p>Progress is not a perfect score. It is a clearer view of what you are doing and what is becoming easier.</p></div><div className="public-pattern-panel"><div className="public-pattern-labels"><span>OVER TIME</span><strong>Your pattern gets clearer</strong></div><div className="public-pattern-bars" aria-label="Illustrative progress pattern"><i/><i/><i/><i/><i/><i/><i/><i className="current"/></div><div className="public-pattern-footer"><span>Meals noticed</span><span>Actions kept</span><span>Movement recorded</span><span>Patterns understood</span></div></div></section>

    <section className="public-evidence-section public-section" aria-labelledby="evidence-title"><div><span className="public-kicker">BUILT AROUND WHAT THE EVIDENCE SAYS</span><h2 id="evidence-title">Useful guidance. Honest limits.</h2></div><div className="public-evidence-copy"><p>Healthy eating is not one perfect plate. The World Health Organization describes healthy dietary patterns through adequacy, balance, moderation, and diversity, with variety across vegetables, fruits, pulses, whole grains, and other nutritious foods.</p><p>Movement counts in many forms. WHO recommends adults work toward 150–300 minutes of moderate activity a week, while noting that any amount is better than none.</p><div className="public-source-links"><a href="https://www.who.int/news-room/fact-sheets/detail/healthy-diet" target="_blank" rel="noreferrer">WHO: Healthy diet ↗</a><a href="https://www.who.int/news-room/fact-sheets/detail/physical-activity" target="_blank" rel="noreferrer">WHO: Physical activity ↗</a></div></div></section>

    <section className="public-trust-section public-section" aria-labelledby="trust-title"><div><span className="public-kicker">TRUST MATTERS</span><h2 id="trust-title">Your health information deserves care.</h2></div><div><p>Neulifi is a nutrition and lifestyle companion, not a doctor. It does not diagnose conditions, predict disease risk from one meal, or replace professional care.</p><p className="public-trust-quote">What Neulifi observes, what evidence tells us, and what you might try next should never be blurred together.</p></div></section>

    <section className="public-bottom-cta public-bottom-cta-premium"><div><span className="public-kicker">START WITH YOUR NEXT MEAL</span><h2>Make health feel more doable.</h2><p>Build a private space for better information, better next choices, and a healthier rhythm.</p></div><button className="button button-green" type="button" onClick={() => onAuth("signup")}>Get started free <span aria-hidden="true">→</span></button></section>
  </main>;
}

function ProductPreview() {
  return <div className="public-product-preview public-product-preview-premium redesigned-product-preview preview-live-card" aria-label="Neulifi app preview"><div className="preview-floating-chip preview-chip-top">YOUR PRIVATE HEALTH SPACE</div><div className="preview-live-header"><div className="preview-live-brand"><BrandMark className="preview-mini-logo"/><span>Neulifi</span></div><span className="preview-live-status"><i aria-hidden="true"/> Ready when you are</span></div><div className="preview-live-body"><aside className="preview-live-rail" aria-hidden="true"><i className="active"/><i/><i/><i/><i/></aside><div className="preview-live-content"><div className="preview-live-top"><span>YOUR SPACE</span><span>Private by design</span></div><div className="preview-live-greeting"><small>START WITH WHAT IS IN FRONT OF YOU</small><strong>Your next useful choice starts here.</strong><p>Analyse a meal, save the observation, and build a clearer picture over time.</p></div><div className="preview-live-empty-grid"><div className="preview-live-empty-card"><small>AVERAGE MEAL BALANCE</small><strong>—</strong><span>No meals yet</span></div><div className="preview-live-empty-card"><small>DAY STREAK</small><strong>0</strong><span>Begins with your first action</span></div></div><div className="preview-live-capture"><span className="preview-live-capture-icon">＋</span><span><strong>Analyse your first meal</strong><small>Photo or upload · approximate signals</small></span><b aria-hidden="true">→</b></div><div className="preview-live-foot"><span>Meal history</span><span>Actions</span><span>Insights</span><em>Builds with you</em></div></div></div><div className="preview-floating-chip preview-chip-bottom"><span>✓</span> No invented data</div></div>;
}

function LoopStep({ number, label, copy }: { number: string; label: string; copy: string }) {
  return <article className="public-loop-step"><span>{number}</span><h3>{label}</h3><p>{copy}</p></article>;
}

function Signal({ label, value, tone }: { label: string; value: string; tone: "good" | "watch" | "neutral" }) {
  return <div className="public-signal"><span>{label}</span><strong className={tone}>{value}</strong></div>;
}

function Features({ onAuth }: { onAuth: (mode: "signin" | "signup") => void }) {
  const featureCards: [string, string, string][] = [["01", "Take a photo", "Show Neulifi the meal in front of you."], ["02", "See the useful signals", "Get clear estimates, not made-up precision."], ["03", "Pick one next step", "Keep the meal. Change one thing."], ["04", "Add your context", "Bring your goals, allergies, and preferences."], ["05", "Move through your day", "Walks, rides, chores, and workouts all count."], ["06", "Notice your pattern", "See what becomes easier over time."]];
  return <main className="public-main"><section className="public-page-heading redesigned-page-heading"><span className="public-kicker">HOW IT WORKS</span><h1>Six simple steps to a clearer day.</h1><p>Neulifi helps you move from a meal photo to one useful next choice, then notice the pattern as you keep going.</p></section><section className="feature-grid feature-grid-redesigned">{featureCards.map(([number, heading, description]) => <article className="feature-card" key={number}><span>{number}</span><h2>{heading}</h2><p>{description}</p></article>)}</section><section className="feature-gallery"><div className="feature-gallery-heading"><span className="public-kicker">INSIDE THE APP</span><h2>See the flow before you start.</h2><p>Simple screens. Real actions. No pressure to be perfect.</p></div><div className="feature-gallery-grid"><FeatureFrame variant="home" title="Your space" caption="Keep meals, actions, and insights together."/><FeatureFrame variant="analyse" title="Your next meal" caption="Start with a photo of what you are actually eating."/><FeatureFrame variant="insight" title="Your pattern" caption="Look back with more clarity, not more guilt."/></div></section><section className="public-privacy redesigned-privacy"><div><span className="public-kicker">YOUR SPACE, YOUR CONTEXT</span><h2>Private information should feel private.</h2></div><p>Neulifi keeps account data behind Supabase authentication and uses the health context you provide to shape the app’s analysis. It does not replace a clinician, diagnose conditions, or prescribe treatment.</p></section><section className="public-bottom-cta"><h2>Start with a clearer next choice.</h2><button className="button button-green" type="button" onClick={() => onAuth("signup")}>Create your free space <span aria-hidden="true">→</span></button></section></main>;
}

function FeatureFrame({ variant, title, caption }: { variant: "home" | "analyse" | "insight"; title: string; caption: string }) {
  return <article className={`feature-frame feature-frame-${variant}`}><div className="feature-frame-top"><span className="feature-frame-dot"/><span className="feature-frame-dot"/><span className="feature-frame-dot"/><small>neulifi / {variant}</small></div><div className="feature-frame-body"><div className="feature-frame-rail"><BrandMark className="feature-frame-logo"/><i/><i/><i/><i/></div><div className="feature-frame-content"><span className="feature-frame-kicker">{variant === "home" ? "OVERVIEW" : variant === "analyse" ? "ANALYSE" : "INSIGHTS"}</span><h3>{title}</h3>{variant === "home" && <><div className="feature-frame-balance"><small>MEAL BALANCE</small><strong>—</strong><span>No meals yet</span></div><div className="feature-frame-row"><b>MEALS</b><b>ACTIONS</b><b>INSIGHTS</b></div></>}{variant === "analyse" && <><div className="feature-frame-upload"><span>＋</span><strong>Your meal photo<br/>will appear here</strong><small>Photo or upload</small></div><div className="feature-frame-actions"><span>Take photo</span><span>Upload</span></div></>}{variant === "insight" && <><div className="feature-frame-chart"><i/><i/><i/><i/><i/><i/></div><div className="feature-frame-insight-row"><span>Meal history</span><strong>Builds with you</strong></div></>}</div></div><div className="feature-frame-caption"><strong>{caption}</strong><span aria-hidden="true">↗</span></div></article>;
}

function Pricing({ onAuth }: { onAuth: (mode: "signin" | "signup") => void }) {
  return <main className="public-main"><section className="public-page-heading pricing-heading pricing-heading-premium"><span className="public-kicker">SIMPLE PLAN PREVIEW</span><h1>More room for the rhythm you are building.</h1><p>Start with the essentials, then add more perspective when it helps you stay consistent. Annual pricing is shown clearly; billing is not connected yet.</p><div className="pricing-billing-note"><span>Annual billing</span><small>Simple plans, no hidden commitments</small></div></section><section className="plan-grid plan-grid-premium">{plans.map((plan) => <PlanCard key={plan.id} plan={plan} highlighted={plan.id === "premium"} onAuth={onAuth} />)}</section><p className="pricing-note">Checkout is not connected yet. These are the intended annual prices and plan boundaries; billing will be enabled only after the payment provider is connected.</p></main>;
}

function PlanCard({ plan, highlighted, onAuth }: { plan: ReturnType<typeof getPlan>; highlighted: boolean; onAuth: (mode: "signin" | "signup") => void }) {
  const id = plan.id as PlanId;
  const annualPrice = plan.annualPrice;
  return <article className={`plan-card plan-card-premium ${highlighted ? "highlighted" : ""}`}><div className="plan-card-top"><span className="plan-label">{plan.name}</span>{highlighted && <span className="plan-popular">BEST VALUE</span>}</div><p>{plan.description}</p><div className="plan-price">{annualPrice === null ? plan.priceLabel : `$${annualPrice}`}<small>{annualPrice === null ? "" : " / year"}</small></div>{plan.price !== null && <div className="plan-monthly-anchor">${plan.price} monthly plan · billed annually</div>}<div className="plan-features plan-features-premium">{plan.marketingFeatures.map((feature, index) => <span className={index === 0 ? "plan-feature-emphasis" : ""} key={feature}>✓ {feature}</span>)}</div><button className={`button ${highlighted ? "button-green" : "button-soft"}`} type="button" onClick={() => onAuth("signup")}>{id === "free" ? "Start free" : "Get started"}</button></article>;
}

function PublicFooter({ onNavigate, onAuth }: { onNavigate: (page: PublicPage) => void; onAuth: (mode: "signin" | "signup") => void }) {
  return <footer className="public-footer"><div><button className="public-brand" type="button" onClick={() => onNavigate("landing")}><BrandMark className="brand-logo"/><strong>Neulifi</strong></button><p>A calmer, more practical way to build health awareness.</p></div><div className="public-footer-links"><button type="button" onClick={() => onNavigate("features")}>How it works</button><button type="button" onClick={() => onNavigate("pricing")}>Plans</button><button type="button" onClick={() => onAuth("signin")}>Sign in</button></div><small>© {new Date().getFullYear()} Neulifi. Nutrition and lifestyle guidance, not medical care.</small></footer>;
}
