import type { ReactNode } from "react";
import { getPlan, plans, type PlanId } from "../lib/plans";

type PublicPage = "landing" | "features" | "pricing";

export function PublicSite({ page, onNavigate, onAuth, onPreview }: { page: PublicPage; onNavigate: (page: PublicPage) => void; onAuth: (mode: "signin" | "signup") => void; onPreview: () => void }) {
  const title = page === "features" ? "A calmer way to understand your meals" : page === "pricing" ? "Choose the amount of support that fits" : "Build a healthier rhythm, one meal at a time";
  return <div className="public-site">
    <PublicNav page={page} onNavigate={onNavigate} onAuth={onAuth}/>
    {page === "landing" ? <Landing title={title} onNavigate={onNavigate} onAuth={onAuth} onPreview={onPreview}/> : page === "features" ? <Features title={title} onAuth={onAuth}/> : <Pricing title={title} onAuth={onAuth}/>} 
    <PublicFooter onNavigate={onNavigate} onAuth={onAuth}/>
  </div>;
}

function PublicNav({ page, onNavigate, onAuth }: { page: PublicPage; onNavigate: (page: PublicPage) => void; onAuth: (mode: "signin" | "signup") => void }) {
  return <header className="public-nav"><button className="public-brand" type="button" onClick={() => onNavigate("landing")}><span className="brand-mark">⌁</span><strong>Nuelifi</strong></button><nav className="public-links" aria-label="Public navigation"><button className={page === "features" ? "active" : ""} type="button" onClick={() => onNavigate("features")}>Features</button><button className={page === "pricing" ? "active" : ""} type="button" onClick={() => onNavigate("pricing")}>Plans</button></nav><div className="public-actions"><button className="public-login" type="button" onClick={() => onAuth("signin")}>Sign in</button><button className="button button-green public-cta" type="button" onClick={() => onAuth("signup")}>Get started</button></div></header>;
}

function Landing({ title, onNavigate, onAuth, onPreview }: { title: string; onNavigate: (page: PublicPage) => void; onAuth: (mode: "signin" | "signup") => void; onPreview: () => void }) {
  return <main className="public-main"><section className="public-hero"><div className="public-hero-copy"><span className="public-kicker">YOUR EVERYDAY HEALTH COMPANION</span><h1>{title}</h1><p>Understand what is on your plate, turn useful observations into simple steps, and keep your progress in one private space.</p><div className="public-hero-actions"><button className="button button-green" type="button" onClick={() => onAuth("signup")}>Create your free space <span aria-hidden="true">→</span></button><button className="public-secondary-cta" type="button" onClick={() => onNavigate("features")}>See how it works</button></div><small className="public-trust">Private by design · practical, not prescriptive · start free</small></div><ProductPreview/></section><section className="public-proof"><div><strong>One clear view</strong><span>Meals, daily actions, and patterns together.</span></div><div><strong>Context-aware</strong><span>Guidance respects the context you choose to share.</span></div><div><strong>Low pressure</strong><span>Small, repeatable steps instead of perfection.</span></div></section><section className="public-section public-split"><div><span className="public-kicker">A BETTER DAILY LOOP</span><h2>Notice what helps. Keep what works.</h2><p>Nuelifi turns a meal photo into an understandable snapshot, then keeps the useful part separate: meal guidance for your next choice and day-level actions you can actually do today.</p><button className="text-button public-text-button" type="button" onClick={() => onNavigate("features")}>Explore the product <span aria-hidden="true">→</span></button></div><div className="public-callout"><span className="public-callout-mark">✦</span><strong>Make health feel more doable.</strong><p>Less noise, more signal, and a place to return to tomorrow.</p></div></section></main>;
}

function ProductPreview() {
  return <div className="public-product-preview" aria-label="Illustration of the Nuelifi product"><div className="preview-window-bar"><span/><span/><span/></div><div className="preview-window-body"><div className="preview-mini-rail"><span className="preview-mini-logo">⌁</span><i/><i/><i/><i/><i/></div><div className="preview-mini-content"><div className="preview-mini-top"><span>OVERVIEW</span><b>SC</b></div><div className="preview-mini-greeting"><small>MONDAY, JUN 16</small><strong>Good morning, Sarah</strong></div><div className="preview-mini-score"><small>AVERAGE HEALTH SCORE</small><strong>82 <em>/100</em></strong><span><i/></span><label>3 meals analysed <b>4/6 actions done</b></label></div><div className="preview-mini-stats"><div><small>MEALS</small><strong>12</strong></div><div><small>ACTIONS</small><strong>8/11</strong></div><div><small>STREAK</small><strong>5d</strong></div></div><div className="preview-mini-capture"><b>＋</b><span><strong>Analyse a meal</strong><small>Photo or upload — takes 10 seconds</small></span><i>→</i></div></div></div></div>;
}

function Features({ title, onAuth }: { title: string; onAuth: (mode: "signin" | "signup") => void }) {
  const featureCards: [string, string, string][] = [["01", "Analyse without overwhelm", "See the important signals from a meal photo in language that is clear, calm, and easy to return to."], ["02", "Keep guidance in its place", "Meal-specific observations stay with the meal. Practical hydration, movement, sleep, and planning steps become tasks only when you choose."], ["03", "Bring your context", "Add the conditions, allergies, preferences, and goals you already know so guidance can be more relevant without pretending to diagnose."], ["04", "Build your own history", "Your private dashboard connects meals, actions, and insights so progress can feel visible over time."]];
  return <main className="public-main"><section className="public-page-heading"><span className="public-kicker">THE PRODUCT</span><h1>{title}</h1><p>Nuelifi is designed around the space between information and action: enough context to be useful, never so much that everyday health becomes another full-time job.</p></section><section className="feature-grid">{featureCards.map(([number, heading, description]) => <article className="feature-card" key={number}><span>{number}</span><h2>{heading}</h2><p>{description}</p></article>)}</section><section className="public-privacy"><div><span className="public-kicker">YOUR SPACE, YOUR CONTEXT</span><h2>Private information should feel private.</h2></div><p>Nuelifi keeps account data behind Supabase authentication and uses the health context you provide only to shape the app’s analysis. It does not replace a clinician, diagnose conditions, or prescribe treatment.</p></section><section className="public-bottom-cta"><h2>Ready for a calmer starting point?</h2><button className="button button-green" type="button" onClick={() => onAuth("signup")}>Create your free space <span aria-hidden="true">→</span></button></section></main>;
}

function Pricing({ title, onAuth }: { title: string; onAuth: (mode: "signin" | "signup") => void }) {
  return <main className="public-main"><section className="public-page-heading pricing-heading"><span className="public-kicker">SIMPLE PLAN PREVIEW</span><h1>{title}</h1><p>Start with the core Nuelifi experience. Pro and Premium are shown honestly as planned tiers while billing is being connected.</p></section><section className="plan-grid">{plans.map((plan) => <PlanCard key={plan.id} plan={plan} highlighted={plan.id === "pro"} onAuth={onAuth}/>)}</section><p className="pricing-note">No payment is collected in this preview. Plan entitlements and analysis allowances are enforced server-side; checkout will be enabled only after the payment provider is connected.</p></main>;
}

function PlanCard({ plan, highlighted, onAuth }: { plan: ReturnType<typeof getPlan>; highlighted: boolean; onAuth: (mode: "signin" | "signup") => void }) {
  return <article className={`plan-card ${highlighted ? "highlighted" : ""}`}><div className="plan-card-top"><span className="plan-label">{plan.name}</span>{highlighted && <span className="plan-popular">PLANNED</span>}</div><p>{plan.description}</p><div className="plan-price">{plan.price === null ? plan.priceLabel : `$${plan.price}`}<small>{plan.price === null ? "" : ` / ${plan.billingInterval}`}</small></div><div className="plan-limit">{plan.aiUsageLimit} AI meal analyses per month</div><div className="plan-features">{plan.capabilities.slice(0, 4).map((capability) => <span key={capability}>✓ {capability.replace(/_/g, " ")}</span>)}</div><button className={`button ${highlighted ? "button-green" : "button-soft"}`} type="button" onClick={() => onAuth("signup")}>{plan.id === "free" ? "Start free" : "Join the waitlist"}</button></article>;
}

function PublicFooter({ onNavigate, onAuth }: { onNavigate: (page: PublicPage) => void; onAuth: (mode: "signin" | "signup") => void }) {
  return <footer className="public-footer"><div><button className="public-brand" type="button" onClick={() => onNavigate("landing")}><span className="brand-mark">⌁</span><strong>Nuelifi</strong></button><p>A calmer, more practical way to build health awareness.</p></div><div className="public-footer-links"><button type="button" onClick={() => onNavigate("features")}>Features</button><button type="button" onClick={() => onNavigate("pricing")}>Plans</button><button type="button" onClick={() => onAuth("signin")}>Sign in</button></div><small>© {new Date().getFullYear()} Nuelifi. Plan preview — billing is not connected.</small></footer>;
}
