const ratings = new Set(["Excellent", "Good", "Reasonable", "Needs Adjustment"]);

function number(value, fallback = 0) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : fallback; }
function bounded(value, minimum, maximum, fallback = minimum) { return Math.max(minimum, Math.min(maximum, number(value, fallback))); }
function portionScale(value) { const parsed = number(value, 2); return parsed > 3 ? bounded(parsed / 100 * 3, 0, 3, 2) : bounded(parsed, 0, 3, 2); }
function normalizeMealAnalysis(input) {
  let raw = typeof input === "string" ? input : JSON.stringify(input);
  const thinkEnd = raw.lastIndexOf("</think>");
  if (thinkEnd >= 0) raw = raw.slice(thinkEnd + "</think>".length);
  const firstBrace = raw.indexOf("{");
  const lastBrace = raw.lastIndexOf("}");
  if (firstBrace >= 0 && lastBrace > firstBrace) raw = raw.slice(firstBrace, lastBrace + 1);
  const parsed = typeof input === "string" ? JSON.parse(raw.replace(/^```json\s*/i, "").replace(/```\s*$/i, "").trim()) : input;
  if (!parsed || typeof parsed !== "object") throw new Error("AI returned an invalid analysis object");
  const indicators = parsed.indicators && typeof parsed.indicators === "object" ? parsed.indicators : {};
  const recommendations = Array.isArray(parsed.recommendations) ? parsed.recommendations.map((item) => String(item).trim()).filter(Boolean).slice(0, 4) : [];
  if (recommendations.length < 2) throw new Error("AI returned too few recommendations");
  return {
    rating: ratings.has(parsed.rating) ? parsed.rating : "Reasonable",
    score: Math.round(bounded(parsed.score, 0, 100, 60)),
    indicators: { calories: bounded(indicators.calories, 0, 3000), protein: bounded(indicators.protein, 0, 250), carbohydrates: bounded(indicators.carbohydrates, 0, 400), fats: bounded(indicators.fats, 0, 200), vegetables: bounded(indicators.vegetables, 0, 10), fibre: bounded(indicators.fibre, 0, 100), sugar: bounded(indicators.sugar, 0, 200), sodium: bounded(indicators.sodium, 0, 5000), portionBalance: portionScale(indicators.portionBalance) },
    explanation: String(parsed.explanation || "This meal has a few strengths and a few practical opportunities for your next choice."),
    recommendations,
  };
}

function base64FromBytes(buffer) { const bytes = new Uint8Array(buffer); let binary = ""; const chunk = 0x8000; for (let i = 0; i < bytes.length; i += chunk) binary += String.fromCharCode(...bytes.subarray(i, Math.min(i + chunk, bytes.length))); return btoa(binary); }
async function imageDataUrl(imageUrl) { if (imageUrl.startsWith("data:")) return imageUrl; const response = await fetch(imageUrl); if (!response.ok) throw new Error(`Meal image could not be fetched (${response.status})`); const mimeType = response.headers.get("content-type")?.split(";")[0] || "image/jpeg"; return `data:${mimeType};base64,${base64FromBytes(await response.arrayBuffer())}`; }
async function geminiImagePart(imageUrl) { const match = imageUrl.match(/^data:([^;]+);base64,(.+)$/); if (!match) throw new Error("Invalid meal image data"); return { inline_data: { mime_type: match[1], data: match[2] } }; }
function mealPrompt(mealName) { return `You are Nuelifi, a calm food and lifestyle companion. The output is machine-read and persisted by the application. Never address the user directly and never diagnose disease. Analyse the meal called "${mealName}". Be practical, non-judgmental, and cautious. Nutrition values are estimates. Return only JSON with rating (Excellent, Good, Reasonable, or Needs Adjustment), score (integer 0-100), indicators (numeric calories, protein, carbohydrates, fats, vegetables, fibre, sugar, sodium, portionBalance), explanation, and 2 to 4 concise actionable recommendations.`; }

async function analyzeGroq(env, imageUrl, mealName) {
  if (!env.GROQ_API_KEY) return null;
  const image = await imageDataUrl(imageUrl);
  const response = await fetch(env.GROQ_BASE_URL || "https://api.groq.com/openai/v1/chat/completions", { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${env.GROQ_API_KEY}` }, body: JSON.stringify({ model: env.GROQ_MODEL || "qwen/qwen3.6-27b", temperature: 0.2, top_p: 0.8, max_completion_tokens: 2200, reasoning_format: "hidden", reasoning_effort: "none", response_format: { type: "json_object" }, messages: [{ role: "user", content: [{ type: "text", text: mealPrompt(mealName) }, { type: "image_url", image_url: { url: image } }] }] }) });
  if (!response.ok) throw new Error(`Groq analysis failed (${response.status})`);
  const payload = await response.json();
  const content = payload.choices?.[0]?.message?.content;
  if (!content) throw new Error("Groq returned no analysis");
  return normalizeMealAnalysis(content);
}

function geminiBody(image, mealName) { return { contents: [{ role: "user", parts: [image, { text: mealPrompt(mealName) }] }], generationConfig: { temperature: 0.2, responseMimeType: "application/json", responseSchema: { type: "OBJECT", properties: { rating: { type: "STRING", enum: ["Excellent", "Good", "Reasonable", "Needs Adjustment"] }, score: { type: "INTEGER", minimum: 0, maximum: 100 }, indicators: { type: "OBJECT", properties: { calories: { type: "NUMBER" }, protein: { type: "NUMBER" }, carbohydrates: { type: "NUMBER" }, fats: { type: "NUMBER" }, vegetables: { type: "NUMBER" }, fibre: { type: "NUMBER" }, sugar: { type: "NUMBER" }, sodium: { type: "NUMBER" }, portionBalance: { type: "NUMBER" } }, required: ["calories", "protein", "carbohydrates", "fats", "vegetables", "fibre", "sugar", "portionBalance"] }, explanation: { type: "STRING" }, recommendations: { type: "ARRAY", items: { type: "STRING" }, minItems: 2, maxItems: 4 } }, required: ["rating", "score", "indicators", "explanation", "recommendations"] } } }; }
async function analyzeGemini(env, imageUrl, mealName) { if (!env.GEMINI_API_KEY) return null; const image = await geminiImagePart(imageUrl); const models = [...new Set([env.GEMINI_MODEL || "gemini-3.7-flash", ...(env.GEMINI_FALLBACK_MODELS || "gemini-3.5-flash,gemini-2.5-flash").split(",").map((item) => item.trim()).filter(Boolean)])]; let lastError; for (const model of models) { const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(env.GEMINI_API_KEY)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(geminiBody(image, mealName)) }); if (response.ok) { const payload = await response.json(); const text = payload.candidates?.[0]?.content?.parts?.map((part) => part.text || "").join(""); if (!text) throw new Error("Gemini returned no analysis"); return normalizeMealAnalysis(text); } lastError = new Error(`Gemini analysis failed (${response.status})`); } throw lastError || new Error("No Gemini model was available"); }

async function verifyUser(request, env) { if (String(env.REQUIRE_AUTH ?? "true").toLowerCase() === "false") return { id: "preview-user" }; const header = request.headers.get("authorization") || ""; const token = header.match(/^Bearer\s+(.+)$/i)?.[1]; if (!token) throw new Error("Authentication required"); const supabaseUrl = env.SUPABASE_URL || env.VITE_SUPABASE_URL; const publishableKey = env.SUPABASE_PUBLISHABLE_KEY || env.VITE_SUPABASE_PUBLISHABLE_KEY; if (!supabaseUrl || !publishableKey) throw new Error("Supabase authentication is not configured"); const response = await fetch(`${supabaseUrl.replace(/\/$/, "")}/auth/v1/user`, { headers: { apikey: publishableKey, authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error("Your session is not valid. Please sign in again."); return response.json(); }
function json(body, status, request, env) { const origin = env.FRONTEND_ORIGIN || request.headers.get("origin") || "*"; return new Response(status === 204 ? null : JSON.stringify(body), { status, headers: { "content-type": "application/json; charset=utf-8", "access-control-allow-origin": origin, "access-control-allow-headers": "authorization, content-type", "access-control-allow-methods": "POST, OPTIONS" } }); }
function assetContentType(pathname, fallback) { if (pathname === "/" || pathname.endsWith(".html")) return "text/html; charset=utf-8"; if (pathname.endsWith(".js")) return "application/javascript; charset=utf-8"; if (pathname.endsWith(".css")) return "text/css; charset=utf-8"; if (pathname.endsWith(".txt")) return "text/plain; charset=utf-8"; return fallback || "application/octet-stream"; }
async function serveAsset(request, env) { const response = await env.ASSETS.fetch(request); const headers = new Headers(response.headers); headers.set("content-type", assetContentType(new URL(request.url).pathname, headers.get("content-type"))); return new Response(response.body, { status: response.status, statusText: response.statusText, headers }); }

export default { async fetch(request, env) { const url = new URL(request.url); if (request.method === "OPTIONS") return json({}, 204, request, env); if (url.pathname === "/health") return json({ status: "ok", service: "nuelifi-cloudflare" }, 200, request, env); if (url.pathname === "/api/analyze" && request.method === "POST") { try { await verifyUser(request, env); const body = await request.json(); const imageUrl = typeof body.imageUrl === "string" ? body.imageUrl : ""; const mealName = typeof body.mealName === "string" && body.mealName.trim() ? body.mealName.trim().slice(0, 120) : "Meal"; if (!imageUrl || (!imageUrl.startsWith("data:image/") && !/^https?:\/\//i.test(imageUrl))) return json({ error: "A valid meal image is required." }, 400, request, env); if (imageUrl.length > 14_000_000) return json({ error: "This image is too large. Choose a smaller photo and try again." }, 413, request, env); let analysis; let provider = ""; const providerErrors = []; try { analysis = await analyzeGroq(env, imageUrl, mealName); if (analysis) provider = "groq"; } catch (error) { providerErrors.push(error instanceof Error ? error.message : String(error)); } if (!analysis) { try { analysis = await analyzeGemini(env, imageUrl, mealName); if (analysis) provider = "gemini"; } catch (error) { providerErrors.push(error instanceof Error ? error.message : String(error)); } } if (!analysis) return json({ error: providerErrors.join("; ") || "No AI provider is configured." }, 502, request, env); return json({ id: `cloudflare-meal-${Date.now()}`, userId: "", imageUrl, mealName, capturedAt: new Date().toISOString(), status: "analysed", provider, analysis }, 200, request, env); } catch (error) { const message = error instanceof Error ? error.message : "Meal analysis failed"; return json({ error: message }, /Authentication|required|session/i.test(message) ? 401 : 500, request, env); } } if (env.ASSETS) return serveAsset(request, env); return new Response("Nuelifi", { status: 200, headers: { "content-type": "text/plain" } }); } };
