import { useEffect, useMemo, useState } from "react";
import { demoDashboard, nuelifiApi, type Action, type Dashboard, type Meal } from "./lib/api";

type Screen = "home" | "analyse" | "actions" | "insights" | "profile";

const icon = (name: string, size = 18) => {
  const paths: Record<string, string> = {
    home: "M3 10.7 12 3l9 7.7v8.8a1.5 1.5 0 0 1-1.5 1.5h-5v-6h-5v6h-5A1.5 1.5 0 0 1 3 19.5z",
    camera: "M4 7.5h3l1.2-2h7.6l1.2 2h3A1.8 1.8 0 0 1 22 9.3v9.2a1.8 1.8 0 0 1-1.8 1.8H3.8A1.8 1.8 0 0 1 2 18.5V9.3a1.8 1.8 0 0 1 1.8-1.8zM12 17a3.6 3.6 0 1 0 0-7.2A3.6 3.6 0 0 0 12 17z",
    check: "M20 6 9 17l-5-5",
    chart: "M4 19V5m0 14h16M8 16v-5m4 5V7m4 9v-8",
    user: "M20 21a8 8 0 0 0-16 0m8-10a4 4 0 1 0 0-8 4 4 0 0 0 0 8z",
    arrow: "m9 18 6-6-6-6",
    upload: "M12 16V4m0 0L7 9m5-5 5 5M4 20h16",
    flame: "M12 21a6 6 0 0 0 6-6c0-4-3-5-3-9-2 1-3 3-3 5-2-1-3-3-3-6-3 3-4 6-4 9a7 7 0 0 0 7 7z",
    leaf: "M20 4C11 4 5 8 5 14c0 3 2 5 5 5 6 0 10-6 10-15zM4 21c2-5 6-8 11-11",
    sun: "M12 3v2m0 14v2M3 12h2m14 0h2m-3.6-6.4 1.4-1.4M5.2 18.8l1.4-1.4m0-10.4L5.2 5.6m13.6 13.2-1.4-1.4M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0z",
  };
  return <svg aria-hidden="true" className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name] || paths.home} /></svg>;
};

function Badge({ children, tone = "green" }: { children: React.ReactNode; tone?: "green" | "gold" | "blue" | "dark" }) { return <span className={`badge badge-${tone}`}>{children}</span>; }
function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`card ${className}`}>{children}</section>; }
function SectionTitle({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: React.ReactNode }) { return <div className="section-title"> <div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2></div>{action}</div>; }

function Header({ screen, onNavigate }: { screen: Screen; onNavigate: (screen: Screen) => void }) {
  const title = screen === "home" ? "Nuelifi" : screen === "analyse" ? "Analyse" : screen === "actions" ? "Your actions" : screen === "insights" ? "Your insights" : "Profile";
  return <header className="topbar">{screen === "home" ? <div className="brand"><span className="brand-mark">⌁</span><strong>{title}</strong></div> : <button className="back-button" onClick={() => onNavigate("home")}>‹</button>}<div className="topbar-title">{screen !== "home" && <strong>{title}</strong>}</div><div className="topbar-right">{screen === "home" && <Badge tone="gold">♔ Free</Badge>}<button className="avatar-button" onClick={() => onNavigate("profile")}>S</button></div></header>;
}

function BottomNav({ screen, onNavigate }: { screen: Screen; onNavigate: (screen: Screen) => void }) { const items: [Screen, string, string][] = [["home", "Home", "home"], ["analyse", "Analyse", "camera"], ["actions", "Actions", "check"], ["insights", "Insights", "chart"], ["profile", "Profile", "user"]]; return <nav className="bottom-nav">{items.map(([key, label, glyph]) => <button key={key} className={screen === key ? "active" : ""} onClick={() => onNavigate(key)}>{icon(glyph, 18)}<span>{label}</span></button>)}</nav>; }

function Home({ dashboard, onNavigate, offline }: { dashboard: Dashboard; onNavigate: (screen: Screen) => void; offline: boolean }) {
  const first = dashboard.recentMeals[0];
  return <div className="screen home-screen">
    {offline && <div className="preview-note">Preview mode · demo data is being shown</div>}
    <div className="greeting"><div><p className="date-label">WEDNESDAY, AUG 20</p><h1>Good morning, Sarah</h1></div><div className="avatar avatar-large">S</div></div>
    <div className="health-score"><div className="score-head"><div><p className="eyebrow light">TODAY'S HEALTH SCORE</p><div className="big-score">82 <small>/100</small></div></div><span className="trend">↗ +7 from yesterday</span></div><div className="score-track"><span style={{ width: "82%" }} /></div><div className="score-foot"><span>{dashboard.mealsAnalysed + 2} meals analysed</span><span>{dashboard.actionsCompleted}/{dashboard.actionsTotal + 4} actions done</span></div></div>
    <div className="stat-grid"><div className="stat-card"><span className="stat-icon blue">{icon("leaf", 17)}</span><strong>{dashboard.mealsAnalysed + 2}</strong><small>MEALS</small></div><div className="stat-card"><span className="stat-icon teal">{icon("check", 17)}</span><strong>{dashboard.actionsCompleted}/{dashboard.actionsTotal + 4}</strong><small>ACTIONS</small></div><div className="stat-card"><span className="stat-icon amber">{icon("flame", 17)}</span><strong>5d</strong><small>STREAK</small></div></div>
    <button className="capture-card" onClick={() => onNavigate("analyse")}><span className="capture-icon">{icon("camera", 22)}</span><span><strong>Analyse a meal</strong><small>Photo or upload — takes 10 seconds</small></span>{icon("arrow", 20)}</button>
    <SectionTitle title="Today's meals" action={<button className="text-button">See all</button>} />
    {first && <article className="featured-meal"><img src={first.imageUrl || "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80"} alt="Colourful meal"/><div className="featured-overlay"><strong>{first.mealName}</strong><Badge>{first.analysis.rating}</Badge></div><div className="meal-meta"><span>◷ Today, 12:34 PM</span><span>⌁ 510 kcal</span></div></article>}
  </div>;
}

function Analyse({ onNavigate }: { onNavigate: (screen: Screen) => void }) { const [selected, setSelected] = useState<string | null>(null); const examples = [{ name: "Grilled salmon with quinoa", image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=300&q=80" }, { name: "Chicken rice bowl", image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=300&q=80" }, { name: "Noodles with egg", image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=300&q=80" }]; return <div className="screen"><p className="screen-intro">Take a photo or upload an image of your meal. Nuelifi gives you a clear, honest assessment with practical next steps — no guilt, just useful information.</p><div className="upload-zone">{selected ? <img src={selected} alt="Selected meal"/> : <><span className="upload-icon">{icon("camera", 28)}</span><strong>Your meal photo will appear here</strong><small>Use the options below to add a photo</small></>}</div><div className="upload-actions"><button className="button button-dark">{icon("camera", 17)} Take photo</button><button className="button button-soft">{icon("upload", 17)} Upload</button></div><p className="or-label">OR TRY AN EXAMPLE</p><div className="example-row">{examples.map((example) => <button key={example.name} onClick={() => setSelected(example.image)}><img src={example.image} alt={example.name}/></button>)}</div>{selected && <button className="button button-green analyse-submit" onClick={() => onNavigate("home")}>Analyse this meal <span>→</span></button>}</div>; }

function Actions({ dashboard, onComplete }: { dashboard: Dashboard; onComplete: (id: string) => void }) { const tasks: Action[] = [...dashboard.openActions, { id: "water", userId: "demo-user", mealId: null, title: "Drink 8 glasses of water today", completed: false, createdAt: "", completedAt: null }, { id: "walk", userId: "demo-user", mealId: null, title: "Walk for 15 minutes after lunch", completed: false, createdAt: "", completedAt: null }, { id: "veg", userId: "demo-user", mealId: null, title: "Add vegetables to dinner", completed: false, createdAt: "", completedAt: null }, { id: "sugar", userId: "demo-user", mealId: null, title: "Choose a lower-sugar snack", completed: false, createdAt: "", completedAt: null }, { id: "salt", userId: "demo-user", mealId: null, title: "Reduce salt in cooking tonight", completed: false, createdAt: "", completedAt: null }].slice(0, 6); const done = dashboard.actionsCompleted; return <div className="screen"><p className="screen-subtitle">{done} of {tasks.length} completed today</p><div className="progress-card"><div><p className="eyebrow light">TODAY'S PROGRESS</p><div className="progress-track"><span style={{ width: `${(done / tasks.length) * 100}%` }}/></div></div><strong>{Math.round((done / tasks.length) * 100)}%</strong></div><div className="task-list">{tasks.map((task) => <button className="task-row" key={task.id} onClick={() => !task.completed && onComplete(task.id)}><span className="task-icon">{icon(task.title.includes("Walk") ? "flame" : task.title.includes("vegetable") ? "leaf" : "check", 17)}</span><span className="task-title">{task.title}</span><span className={`task-check ${task.completed ? "done" : ""}`}>{task.completed ? "✓" : ""}</span></button>)}</div></div>; }

function Insights({ dashboard }: { dashboard: Dashboard }) { const values = [72, 85, 61, 78, 90, 55, 82]; const meals = dashboard.recentMeals; return <div className="screen"><p className="screen-subtitle">Last 7 days of eating patterns</p><div className="stat-grid insight-stats"><div className="stat-card"><strong className="green-text">75<small>/100</small></strong><small>AVG. SCORE</small></div><div className="stat-card"><strong className="blue-text">19</strong><small>MEALS LOGGED</small></div><div className="stat-card"><strong className="orange-text">31</strong><small>ACTIONS DONE</small></div></div><Card className="chart-card"><h3>Health score — 7 days</h3><div className="chart"><div className="chart-y"><span>100</span><span>85</span><span>70</span><span>55</span><span>40</span></div><svg viewBox="0 0 320 150" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#2ca66f" stopOpacity=".2"/><stop offset="1" stopColor="#2ca66f" stopOpacity="0"/></linearGradient></defs><path d="M0 85 C25 55, 35 55, 55 40 S90 110, 110 90 S140 60, 165 58 S195 35, 215 42 S235 120, 260 100 S290 72, 320 48 L320 150 L0 150Z" fill="url(#fill)"/><path d="M0 85 C25 55, 35 55, 55 40 S90 110, 110 90 S140 60, 165 58 S195 35, 215 42 S235 120, 260 100 S290 72, 320 48" fill="none" stroke="#2ca66f" strokeWidth="2.5"/>{values.map((_, i) => <circle key={i} cx={i * 53.3} cy={[85, 40, 90, 58, 42, 100, 48][i]} r="3.5" fill="#2ca66f" stroke="white" strokeWidth="2"/>)}</svg><div className="chart-x"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></Card><SectionTitle title="Recent meals"/><div className="meal-list">{[...meals, ...meals, ...meals].slice(0, 3).map((meal, i) => <div className="meal-list-row" key={`${meal.id}-${i}`}><img src={meal.imageUrl || "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=200&q=80"} alt="Meal"/><div><strong>{["Grilled salmon with quinoa", "Chicken rice with vegetables", "Fried noodles with egg"][i]}</strong><small>{i === 0 ? "Today, 12:34 PM" : i === 1 ? "Today, 7:45 AM" : "Yesterday, 1:10 PM"}</small></div><Badge tone={i === 0 ? "green" : i === 1 ? "blue" : "gold"}>{i === 0 ? "Excellent" : i === 1 ? "Good" : "Reasonable"}</Badge></div>)}</div><Card className="notice-card"><span className="notice-star">☆</span><div><strong>What Nuelifi has noticed</strong><p>Your highest-scoring meals include quality protein and colourful vegetables.</p></div></Card></div>; }

function Profile() { const [notifications, setNotifications] = useState(true); const [reminders, setReminders] = useState(true); return <div className="screen profile-screen"><div className="profile-head"><div className="avatar profile-avatar">S</div><h1>Sarah Chen</h1><p>sarah@example.com</p><Badge>• Free plan</Badge></div><Card className="goals-card"><h3>My health goals</h3><div className="goal-tags"><span>Reduce blood sugar</span><span>Eat more vegetables</span><span>Lower cholesterol</span><span>Build consistent habits</span></div></Card><p className="preference-label">PREFERENCES</p><Card className="settings-card"><Setting label="Notifications" description="Meal reminders and tips" value={notifications} onChange={() => setNotifications(!notifications)}/><Setting label="Daily goal reminders" description="Get nudged on incomplete actions" value={reminders} onChange={() => setReminders(!reminders)}/><Setting label="Weekly summary" description="Sunday insights email" value={false} onChange={() => {}}/><div className="setting-row"><div><strong>Appearance</strong><small>Light or dark mode</small></div><span className="appearance">{icon("sun", 14)} Light</span></div></Card><div className="pro-card"><span>♔</span><div><strong>Upgrade to Nuelifi Pro</strong><small>Deeper insights and advanced analysis</small></div><button>→</button></div></div>; }
function Setting({ label, description, value, onChange }: { label: string; description: string; value: boolean; onChange: () => void }) { return <div className="setting-row"><div><strong>{label}</strong><small>{description}</small></div><button className={`switch ${value ? "on" : ""}`} onClick={onChange}><span/></button></div>; }

export default function App() { const [screen, setScreen] = useState<Screen>("home"); const [dashboard, setDashboard] = useState<Dashboard>(demoDashboard()); const [offline, setOffline] = useState(true); const load = () => nuelifiApi.dashboard("demo-user").then((data) => { setDashboard(data); setOffline(false); }).catch(() => { setDashboard(demoDashboard()); setOffline(true); }); useEffect(() => { load(); }, []); const complete = async (id: string) => { if (offline || id.length < 12) { setDashboard((current) => ({ ...current, actionsCompleted: Math.min(current.actionsTotal + 4, current.actionsCompleted + 1), openActions: current.openActions.filter((action) => action.id !== id) })); return; } await nuelifiApi.completeAction(id); load(); }; const page = useMemo(() => screen === "home" ? <Home dashboard={dashboard} onNavigate={setScreen} offline={offline}/> : screen === "analyse" ? <Analyse onNavigate={setScreen}/> : screen === "actions" ? <Actions dashboard={dashboard} onComplete={complete}/> : screen === "insights" ? <Insights dashboard={dashboard}/> : <Profile/>, [screen, dashboard, offline]); return <div className="app-shell"><Header screen={screen} onNavigate={setScreen}/><main>{page}</main><BottomNav screen={screen} onNavigate={setScreen}/></div>; }
